#!/bin/bash
# 
# Batch Control Submission script for auto run stats creation.
#
# see:  https://confluence.slac.stanford.edu/display/PSDM/Automatic+Run+Processing
#

unset DISPLAY XAUTHORITY
export PYTHONPATH=
echo "$@"
source /reg/g/psdm/bin/conda_setup ""

SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do 
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR

EXP=$1
shift
RUN=$1
INSTRUMENT=${EXP:0:3}

shift
if [[ $1 ]]; then
  QUEUEREQ=$1
  shift
  if [[ $1 ]]; then
    PYOPT=$1
    shift
    if [[ $1 ]]; then
      RUNFILE=$1
      shift
    fi
  fi
fi

#PYOPT='test'

: ${DIRNAME:="$DIR/../python/PyDataSource/"}
: ${PYFILE:="__main__.py"}
: ${MAX_SIZE:="10001"}
: ${QUEUEREQ:="psfehq"}
#: ${QUEUEREQ="psdebugq"}
OUTDIR="/reg/d/psdm/$INSTRUMENT/$EXP/scratch/nc"
RUNSTR=Run`python "$DIRNAME/get_run_from_runid.py" $EXP $RUN`
EXPRUN="$EXP$RUNSTR"
BATCHUSER=`whoami`
#OUTLOG="$OUTDIR/logs/$RUNSTR"
OUTLOG="/reg/neh/home/$BATCHUSER/logs/$EXP/$RUNSTR"
if [[ ! -a $OUTLOG ]];  then
    mkdir -p $OUTLOG
fi

if [[ $PYOPT == '' ]]; then 
    JOBNAME="$EXPRUN"
    PYOPT='batch'
    : ${RUNFILE:="$DIRNAME/$PYFILE"}
elif [[ $PYOPT == 'epics' ]]; then 
    JOBNAME="$EXP"epics
    : ${RUNFILE:="$DIRNAME/$PYFILE"}
else
    JOBNAME="$EXPRUN"
    EXPFILE="$PYOPT"
    RUNFILE="/reg/d/psdm/$INSTRUMENT/$EXP/results/src/$EXPFILE.py"
    PYOPT='batch'
fi

# Directories not available on psanasvc01 -- need to ssh to 
#: ${CONFIG:=`ssh psana python "$DIRNAME/get_config_file.py" $EXP $RUN`}
#echo 'Config: '$CONFIG 
CONFIG='auto'

echo Processing $EXP Run $RUN
echo '##' bsub -q "$QUEUEREQ" -J "$JOBNAME" -o $OUTLOG/%J.log python "$RUNFILE" "$PYOPT" --exp="$EXP" --run=$RUN --max_size="$MAX_SIZE" --config="$CONFIG"

LOGSUM=/reg/neh/home/koglin/logs/"$EXP"/batch_jobs.log
echo '--------------------------------' >> $LOGSUM
date >> $LOGSUM
echo Processing $EXP Run $RUN >> $LOGSUM
echo `uname -a` >> $LOGSUM
echo 'User: '$BATCHUSER >> $LOGSUM
echo 'Run:    '$RUNSTR >> $LOGSUM
echo $EXPRUN >> $LOGSUM
echo 'Log Path: '$OUTLOG >> $LOGSUM
echo 'Config: '$CONFIG >> $LOGSUM
echo 'Run File: '$RUNFILE >> $LOGSUM

echo '##' bsub -q "$QUEUEREQ" -J "$JOBNAME" -o $OUTLOG/%J.log python "$RUNFILE" "$PYOPT" --exp="$EXP" --run=$RUN --max_size="$MAX_SIZE" --config="$CONFIG" >> $LOGSUM

bsub -q "$QUEUEREQ" -J "$JOBNAME" -o $OUTLOG/%J.log python "$RUNFILE" "$PYOPT" --exp="$EXP" --run=$RUN --max_size="$MAX_SIZE" --config="$CONFIG" 


